importScripts(
    'core/compat.js',
    'core/omnibox.js',
    'core/query-event.js',
    'core/storage.js',
    'core/command/base.js',
    'core/command/history.js',
    'core/command/manager.js',
    'core/command/open.js',
    'core/command/simple.js',
    'index.js',
    'search.js',
    'main.js',
);